#!/bin/bash
E=/mnt/c/Users/crutkasLocal/.copilot/session-state/c63ab774-a023-4e57-9bc4-53f727507ada/files/evidence
{
echo "# REFUTATION: the '__ctype_b dangling / libc has a hole' finding is WRONG."
echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)   session c63ab774"
echo
echo "## FIRST, AN ARTEFACT-IDENTITY CORRECTION"
echo "  The report was flagged as measured on 'a different artefact from yours',"
echo "  490dfe09..., 30,894,383 bytes. THAT IS MY CURRENT BUILD. Same sha256,"
echo "  same byte count. It is the post-import-fix, post-.xdata, post-pseudo-reloc"
echo "  relink. So the caveat dissolves and the claim applies to me directly --"
echo "  which is exactly why I tested it rather than dismissing it."
echo
echo "## EMPIRICAL RESULT ON THAT EXACT BUILD -- ALL ctype WORKS"
echo "  rung7.exe, one printf per function, flushed, so the last line printed"
echo "  would name any function that died:"
echo "    A strlen  -> 17"
echo "    B abs     -> 42"
echo "    C toupper -> 65"
echo "    D tolower -> 97      <- reported as CRASH"
echo "    E isalpha -> 1       <- reported as CRASH"
echo "    F isdigit -> 1"
echo "    G isspace -> 1"
echo "    H atoi    -> 12345   <- reported as CRASH"
echo "    I strtol  -> 6789"
echo "    ALL CTYPE OK"
echo "  exit 44. No crash. The three functions reported as crashing all return"
echo "  correct values."
echo
echo "## AND THE SYMBOL TABLE READING WAS WRONG IN TWO WAYS"
echo "  CLAIM: '_ctype_ has ZERO occurrences'."
echo "  MEASURED: 12 occurrences, and the table itself IS defined:"
echo "    0000000180244800 D _ctype_b        <- ONE underscore, DEFINED"
echo "                     U __ctype_b       <- TWO underscores, undefined"
echo "  These are DIFFERENT SYMBOLS. The defined one is the real table."
echo
echo "## MECHANISM -- WHY THE UNDEFINED SYMBOL IS BENIGN"
echo "  newlib/libc/ctype/ctype_.c:"
echo "     88   char _ctype_b[128 + 256] = { ...   /* the actual table */"
echo "    102   .set    _ctype_,_ctype_b+127"
echo "    109   .set    __ctype_,__ctype_b+127"
echo "    173   ctype_ptr = _ctype_b;             /* what is actually used */"
echo "  Line 109 is a compatibility alias for targets whose ABI PREPENDS A"
echo "  LEADING UNDERSCORE to C symbols (i386 PE). On aarch64 no underscore is"
echo "  prepended, so '__ctype_b' inside that .set names a symbol that does not"
echo "  exist on this target. It produces a 'U __ctype_b' entry that NOTHING"
echo "  REFERENCES. Confirmed: zero object files in the build reference it, and"
echo "  there are zero source references outside that asm alias block."
echo
echo "## HOW THE FALSE POSITIVE WAS CONSTRUCTED"
echo "  A real observation ('U __ctype_b') was joined to a real observation"
echo "  (three functions crashed) by an assumed causal link that was never"
echo "  tested. The crashes, whatever caused them, were NOT ctype and NOT this"
echo "  symbol -- because on this same binary those functions return correct"
echo "  values. TWO TRUE FACTS AND A FALSE CONNECTIVE."
echo "  Note also the pass/fail split was read as 'exactly the ctype boundary'."
echo "  It is not: toupper/tolower are the SAME newlib implementation family,"
echo "  and isdigit/isspace were never tested in the original report though they"
echo "  use the identical table lookup as isalpha."
echo
echo "## WHAT I DID NOT VERIFY"
echo "  I did not reproduce the original crashes and cannot say what caused"
echo "  them. Per-function isolation under bare LoadLibrary is a different"
echo "  harness from a linked executable, and the earlier getpid()==0 result"
echo "  shows that harness does not fully initialise Cygwin process state."
echo "  That is the likeliest source and it is NOT a libc defect."
} > $E/ctype-finding-refuted.txt
echo "written."
echo
echo "=== remaining fork lead: mini_cygheap layout (chain is at +sizeof(mini_cygheap)) ==="
grep -n "struct mini_cygheap" -A8 /root/xc/w-link/runtime/winsup/cygwin/local_includes/cygheap.h
