#!/bin/bash
E=/mnt/c/Users/crutkasLocal/.copilot/session-state/c63ab774-a023-4e57-9bc4-53f727507ada/files/evidence
{
echo "# REFRAMED: THIS IS NOT A fork DEFECT. IT IS A cygheap DEFECT PRESENT IN"
echo "# EVERY PROCESS. fork IS SIMPLY THE ONLY CODE THAT EVER WALKS THE CHAIN."
echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)   session c63ab774"
echo
echo "## THE DECISIVE EXPERIMENT"
echo "  rung8.exe: printf, malloc, free, then a DELIBERATE null write purely as"
echo "  a capture mechanism. IT NEVER FORKS. Walked cygheap->chain in it:"
echo
echo "    ROOT PROCESS (never forked)"
echo "    cygheap region @0x800000000: COMMITTED size=0x300000"
echo "    cygheap->chain = 0x800021840"
echo "    [38] rvc=0x8000068F0  b=0x6  prev=0x0000008000384000  <== OUT OF CYGHEAP"
echo "         that prev: COMMITTED allocBase=0x8000200000 size=0x8000"
echo "    >>> CHAIN IS UNTERMINATED after 39 entries"
echo
echo "  IDENTICAL SIGNATURE TO THE fork CHILD, SAME ENTRY 0x8000068F0."
echo "  So the chain is already broken before fork is ever called. Every MSYS2"
echo "  process on ARM64 is carrying a corrupt cygheap allocation chain right"
echo "  now; nothing walks it, so nothing notices, until fork does."
echo
echo "## GEOMETRY MEASURED, NOT ASSUMED"
echo "  Compiled a probe against the real headers:"
echo "    sizeof(init_cygheap)    = 0x48A0 (18592)"
echo "    offsetof(chain)         = 8          <- matches the disassembly"
echo "                                            ldr x19,[x0,#8] and my harness"
echo "    sizeof(mini_cygheap)    = 8"
echo "    sizeof(_cmalloc_entry)  = 16"
echo "    offsetof(data)          = 16"
echo "    NBUCKETS                = 32"
echo "  The deepest chain entry sits at cygheap+0x68F0, which is PAST the"
echo "  0x48A0 header, so it is a genuine allocation and not a false positive"
echo "  from walking into the struct. I checked this specifically because my"
echo "  in-heap range test was loose enough to have accepted a header address."
echo
echo "## WHAT THE DEFECT IS, STATED PRECISELY"
echo "  _cmalloc (mm/cygheap.cc:396-398) does, for a newly sbrk'd entry:"
echo "      rvc->b = b;"
echo "      rvc->prev = cygheap->chain;"
echo "      cygheap->chain = rvc;"
echo "  The FIRST such allocation must therefore store prev = NULL, because a"
echo "  freshly VirtualAlloc'd cygheap is zero-filled. IT DOES NOT. The deepest"
echo "  entry's prev holds a pointer into Cygwin's mmap arena"
echo "  (MMAP_STORAGE_LOW = 0x1000000000; observed allocBase 0x8000200000)."
echo "  cygheap_fixup_in_child walks that chain and dereferences it, and in the"
echo "  child that region does not exist, so it faults."
echo
echo "## MEASUREMENTS THAT CONSTRAIN THE CAUSE"
echo "  - The bad value VARIES PER RUN: 0xBD102AE000, 0x80002D1000,"
echo "    0xDDC4F01000, 0x8000316000, 0x8000384000. So it is an OS-chosen"
echo "    address, not a fixed constant, and therefore not a layout bug."
echo "  - It does NOT alias any field of the cygheap header: dumped the first"
echo "    0x140 bytes (locale, chain, all 32 buckets) and hunted for the value."
echo "    No match."
echo "  - _csbrk NEVER calls VirtualAlloc(NULL,..) -- it always commits at a"
echo "    computed newbase -- so _csbrk cannot itself place an entry outside"
echo "    the arena."
echo "  - There is a gap: the header ends at 0x48A0 but the deepest chain entry"
echo "    is at 0x68F0, so ~0x2050 bytes were allocated by direct _csbrk calls"
echo "    that never joined the chain. That is expected, not a defect."
echo
echo "## A STRUCTURAL OBSERVATION, OFFERED AS A LEAD AND NOT AS A CAUSE"
echo "  mm/cygheap.cc:30-35"
echo "     static mini_cygheap NO_COPY cygheap_dummy = { {__utf8_mbtowc} };"
echo "     init_cygheap NO_COPY *cygheap = (init_cygheap *) &cygheap_dummy;"
echo "  Before cygheap_init(), the global cygheap points at an object that is"
echo "  EIGHT BYTES LONG but is typed as init_cygheap, whose chain member is at"
echo "  offset 8. Any read or write of cygheap->chain in that window lands one"
echo "  word PAST cygheap_dummy, in adjacent static data. A read there would"
echo "  yield exactly what is observed: a plausible-looking, per-run-varying"
echo "  pointer to real memory."
echo "  THIS IS NOT PROVEN. It is the same on x86_64, where fork works, so if"
echo "  it is the mechanism then something ARM64-specific must be reaching"
echo "  _cmalloc earlier than upstream expects. I have NOT demonstrated any"
echo "  such early call, and I am not claiming one."
echo
echo "## WHAT I HAVE NOT ESTABLISHED"
echo "  I have not identified what writes the value, and I have not shown that"
echo "  x86_64 differs here. Everything above about the dummy is a hypothesis."
echo "  The measured facts are: the chain is unterminated, in every process,"
echo "  at the first chained allocation, with a per-run-varying mmap-arena"
echo "  pointer, and fork is the only consumer."
} > $E/fork-reframed-cygheap-chain.txt
wc -l $E/fork-reframed-cygheap-chain.txt
