#!/bin/bash
E=/mnt/c/Users/crutkasLocal/.copilot/session-state/c63ab774-a023-4e57-9bc4-53f727507ada/files/evidence
{
echo "# WATCHPOINT ATTEMPT: PARTIAL RESULT, HONESTLY BOUNDED."
echo "# Plus a reusable capability finding for the programme."
echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)   session c63ab774"
echo "# artefact under test, hash re-read at report time:"
echo "#   msys-2.0.dll 490dfe093a6dd2b76723715e85dfb779a85bd6add9b03795f61826ee0a9215cf"
echo "#   rung8.exe    0078cd0fa92813915dbd2e6d22df7448964b7b18c41d7e89ec6daa1a8645d204"
echo
echo "## CAPABILITY FINDING: HARDWARE WATCHPOINTS WORK ON WINDOWS ON ARM"
echo "  This is reusable and nobody in the programme had established it."
echo "  ARM64 CONTEXT is 912 bytes; the debug registers sit at:"
echo "     Bcr[8] @0x318   Bvr[8] @0x338   Wcr[2] @0x378   Wvr[2] @0x380"
echo "  ContextFlags = CONTEXT_ARM64|CONTROL|INTEGER|FP|DEBUG_REGISTERS"
echo "               = 0x0040000F"
echo "  DBGWCR encoding for an 8-byte user-mode WRITE watchpoint:"
echo "     E bit0 =1 | PAC bits2:1 =0b10 (EL0) | LSC bits4:3 =0b10 (store)"
echo "     | BAS bits12:5 =0xFF        ==>  0x1FF5"
echo "  SetThreadContext ACCEPTED it and a GetThreadContext READBACK CONFIRMED"
echo "  it was kept:  Wcr[0]=0x1FF5  Wvr[0]=0x800000008.  It then FIRED."
echo "  I verified the readback rather than trusting the set to have worked,"
echo "  because a platform may silently ignore registers it does not honour."
echo
echo "## WHAT THE WATCHPOINT ESTABLISHED"
echo "  Every hit reported PC = msys-2.0.dll RVA 0xA9000, which addr2line maps"
echo "  to _cmalloc at mm/cygheap.cc:398. Disassembly of the sequence:"
echo "     1800e8ff0  ldr x0, [x2, #8]    ; x0 = cygheap->chain"
echo "     1800e8ff4  str w6, [x5]        ; rvc->b = b        (4-byte store)"
echo "     1800e8ff8  str x0, [x5, #8]    ; rvc->prev = cygheap->chain"
echo "     1800e9000  str x5, [x2, #8]    ; cygheap->chain = rvc   <== WATCHED"
echo
echo "  THIS IS THE IMPORTANT INFERENCE: at 0x1800e8ff8 the value written into"
echo "  rvc->prev is whatever cygheap->chain ALREADY HELD. _cmalloc:398 always"
echo "  stores a valid rvc. SO _cmalloc IS NOT THE CORRUPTER -- IT FAITHFULLY"
echo "  PROPAGATES A VALUE THAT WAS ALREADY WRONG. The corrupting write to"
echo "  cygheap+8 comes from somewhere else, and it is that write the"
echo "  watchpoint was meant to catch."
echo
echo "## WHY IT DID NOT CATCH IT -- STATED PLAINLY, NOT GLOSSED"
echo "  The watchpoint RE-FIRES ON THE SAME INSTRUCTION. Every one of the 38"
echo "  recorded hits reports the identical PC and LR, and the watched location"
echo "  reads 0 each time, so NO FORWARD PROGRESS WAS MADE. Resuming with"
echo "  DBG_CONTINUE re-executes the same store and re-triggers."
echo "  To advance, the handler must disarm, single-step one instruction, and"
echo "  re-arm -- which on AArch64 means driving the Cpsr SS bit or an"
echo "  equivalent, and I did not implement it."
echo "  THEREFORE THE RUN NAMES A KNOWN-LEGITIMATE WRITER AND DOES NOT NAME THE"
echo "  CORRUPTER. I am recording it as a partial result. The 38 identical"
echo "  lines are ONE observation repeated, not 38 observations, and they must"
echo "  not be read as a sequence of distinct writes."
echo
echo "## NEXT INSTRUMENT"
echo "  Either finish the watchpoint (disarm / single-step / re-arm), or run"
echo "  the polling bisect: sample cygheap->chain at points between"
echo "  cygheap_init() and the first surviving allocation and halve the window."
echo "  The target window is already narrow: between cygheap->user.init() and"
echo "  the next _cmalloc."
} > $E/watchpoint-partial.txt
wc -l $E/watchpoint-partial.txt
